name: blog-app # version: (obsolete)

services:
    blog-db:
        image: 'mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - blog-db-vol:/var/lib/mysql
        ports:
            - '3306:3306'
        networks:
            - blog-app-net

    blog-server:
        build:
            dockerfile: 'Dockerfile'
            context: './'
        container_name: 'blog-app-container'
        ports:
            - '3001:3000'
        env_file:
            - ./.env
        volumes:
            - './:/app'
        depends_on:
            - blog-db
        networks:
            - blog-app-net

volumes:
    blog-db-vol:
networks:
    blog-app-net:
      driver: 'bridge'
    